// Generated by ReScript, PLEASE EDIT WITH CARE


window.count = 0;

var plusButton = document.getElementById("plus-one");

var minusButton = document.getElementById("minus-one");

var countElement = document.getElementById("count");

function renderText(n) {
  countElement.innerText = "Count is " + n;
  
}

function changeCountElement(n) {
  window.count = window.count + n | 0;
  if (window.count > 0) {
    return renderText("50");
  } else if (window.count < 0) {
    return renderText("-50");
  } else {
    return renderText("0");
  }
}

function plusOne(param) {
  return changeCountElement(1);
}

function minusOne(param) {
  return changeCountElement(-1);
}

plusButton.addEventListener("click", plusOne);

minusButton.addEventListener("click", minusOne);

export {
  plusButton ,
  minusButton ,
  countElement ,
  renderText ,
  changeCountElement ,
  plusOne ,
  minusOne ,
  
}
/*  Not a pure module */
