// Generated by ReScript, PLEASE EDIT WITH CARE


window.count = 0;

var plusButton = document.getElementById("plus-one");

var minusButton = document.getElementById("minus-one");

var countElement = document.getElementById("count");

var count = {
  contents: 0
};

function changeClassNames(param) {
  if (count.contents > 0) {
    return "count-positive";
  } else if (count.contents < 0) {
    return "count-negative";
  } else {
    return "count-zero";
  }
}

function changeCountElement(n) {
  count.contents = count.contents + n | 0;
  countElement.innerText = "Count is " + String(count.contents);
  countElement.classList = "count " + changeClassNames(undefined);
  
}

function plusOne(param) {
  return changeCountElement(1);
}

function minusOne(param) {
  return changeCountElement(-1);
}

plusButton.addEventListener("click", plusOne);

minusButton.addEventListener("click", minusOne);

export {
  plusButton ,
  minusButton ,
  countElement ,
  count ,
  changeClassNames ,
  changeCountElement ,
  plusOne ,
  minusOne ,
  
}
/*  Not a pure module */
